### PR TITLE
feat: horizon theme

### PR DESCRIPTION
**Pull request by maxmx03**
20241006_04h22m53s_grim

### CODE REVIEW

**Comment by siduck** [comment]
we have dark horizon already! :flushed:

**Comment by maxmx03** [comment]
Ok, sorry

**Comment by siduck** [comment]
is this horizon , this one? https://github.com/jolaleye/horizon-theme-vscode

in theme switcher select dark horizon and show the difference, then i'll see

**Comment by maxmx03** [comment]
> is this horizon , this one? https://github.com/jolaleye/horizon-theme-vscode
> 
> in theme switcher select dark horizon and show the difference, then i'll see

I open another pull request [pr](https://github.com/NvChad/base46/pull/346)

**Pull request closed without merging**
