### PR TITLE
feat: monochrome

### PR DESCRIPTION
**Pull request by nanomoeamezao**
A weak attempt to port https://github.com/kdheepak/monochrome.nvim to base46.

### CODE REVIEW

**Comment by siduck** [comment]
Will test this locally tomorrow, ayu-light is in the queue.

**Comment by nanomoeamezao** [comment]
image

for now it looks like this

**Comment by nanomoeamezao** [comment]
closes #121

**Comment by nanomoeamezao** [comment]
image

This looks somewhat ok. Diff from what the original had, but i like it.

**Comment by nanomoeamezao** [comment]
Oh, sorry, i forgot to disable an addon for the screenshot. I will send more later with it disabled.

**Comment by nanomoeamezao** [comment]
image

Screenshot without rainbow braces

**Comment by siduck** [comment]
@nanomoeamezao sorry for the long delay, i will merge this today

**Review by siduck — APPROVED** [review]

**Pull request merged**
