### PR TITLE
Add radium theme [OC]

### PR DESCRIPTION
**Pull request by pagankeymaster**
## Colorscheme

Following are the colors that are used in this theme.

```lua
local M = {}

M.base_30 = {
   white = "#d4d4d5",
   darker_black = "#11161b",
   black = "#101317", --  nvim bg
   black2 = "#171b20",
   one_bg = "#1a1f24",
   one_bg2 = "#2a2f34",
   one_bg3 = "#32373c",
   grey = "#262d33",
   grey_fg = "#333c44",
   grey_fg2 = "#3f4449",
   light_grey = "#585862",
   red = "#f87070",
   baby_pink = "#ff8e8e",
   pink = "#ffa7a7",
   line = "#292933", -- for lines like vertsplit
   green = "#36c692",
   vibrant_green = "#79dcaa",
   blue = "#7ab0df",
   nord_blue = "#87bdec",
   yellow = "#ffe59e",
   sun = "#ffeda6",
   purple = "#c397d8",
   dark_purple = "#b77ee0",
   teal = "#54ced6",
   orange = "#e5d487",
   cyan = "#70c0ba",
   statusline_bg = "#171b20",
   lightbg = "#282d32",
   lightbg2 = "#22272c",
   pmenu_bg = "#3bdda2",
   folder_bg = "#5fb0fc",
}

M.base_16 = {
   base00 = "#101317",
   base01 = "#171C21",
   base02 = "#1c2026",
   base03 = "#20252b",
   base04 = "#3d464e",
   base05 = "#ced4df",
   base06 = "#333c44",
   base07 = "#3a434b",
   base08 = "#56c69d",
   base09 = "#ffe59e",
   base0A = "#ffeda6",
   base0B = "#79dcaa",
   base0C = "#7ab0df",
   base0D = "#87bdec",
   base0E = "#f87070",
   base0F = "#f78888",
}

M = require("base16").override_theme(M, "radium")

return M
```

## Showcases

Colorscheme in action.

### Telescope

telescope.nvim

## Completion menu

nvim-cmp

nvim-cmp-float-docs

## Misc.

misc

### CODE REVIEW

**Comment by siduck** [comment]
read this https://github.com/NvChad/base46#understanding-theme-variables

ig darkerblack var looks lighter than black color which isnt right imo

**Comment by pagankeymaster** [comment]
> ig darkerblack var looks lighter than black color which isnt right imo

Should I just swap them?

**Comment by siduck** [comment]
> > ig darkerblack var looks lighter than black color which isnt right imo
> 
> Should I just swap them?

no, darker_black is supposed to be darker than black color, check the readme

**Comment by pagankeymaster** [comment]
image

yeah I did read that... it's just this looks quite bad imo what are your thoughts?

**Comment by siduck** [comment]
> image
> 
> yeah I did read that... it's just this looks quite bad imo what are your thoughts?

you dont need to follow the color %'s literaly, thats just an example . just alter the % value so it looks great

**Comment by pagankeymaster** [comment]
decided to go with `#090909` I'll push if everything is okay

**Comment by siduck** [comment]
@pagankeymaster lemme know when it gets done, Would you mind if I flex with this theme in the ricing subreddit?  ofc no! :sunglasses:

**Comment by siduck** [comment]
yea you've done your part, now lemme polish it!

**Comment by pagankeymaster** [comment]
> @pagankeymaster lemme know when it gets done, Would you mind if I flex with this theme in the ricing subreddit? ofc no! sunglasses

by all means! Also, ping me in the discord server when you do!

**Comment by pagankeymaster** [comment]
> yea you've done your part, now lemme polish it!

I just push it (>.<)

**Comment by siduck** [comment]
btw does your theme have any xresouces theme?

**Comment by pagankeymaster** [comment]
Yeah [here](https://github.com/pagankeymaster/nightly/tree/main/config/Xresources) they're in my dots

**Comment by siduck** [comment]
@pagankeymaster can you try these colors, I feel they're better 

https://paste.sh/1zi9Dh4E#ykggQkEUXogwrbEbwDXL25AX

**Comment by pagankeymaster** [comment]
oooh telescope looks quite nice I might modify my original config too

**Comment by pagankeymaster** [comment]
also what is the highlight group of the yellow thing
image

**Comment by siduck** [comment]
oh idk about it, you can install treesitter playground and put cursor on it and run this command 
:TSHighlightCapturesUnderCursor

**Comment by pagankeymaster** [comment]
thanks.

**Comment by siduck** [comment]
image

before vs after

**Comment by siduck** [comment]
btw any good wallpapers for this colorscheme? :thinking:

**Comment by pagankeymaster** [comment]
> image
> 
> before vs after

Ah! mine looked quite green.

> btw any good wallpapers for this colorscheme? thinking
1lzvgynmmpw81
blessing
comets
geo-night
output-1650576075
output-1650576591
output-1650576767
painting

These are the only ones I made for this colorscheme ^

**Comment by pagankeymaster** [comment]
You could try using this though:
```py
#!/usr/bin/env python
"""Converts image to Night colorscheme."""

from datetime import datetime
from os.path import expanduser
from sys import argv

from ImageGoNord import GoNord

with open("./colors.txt", encoding="utf8") as file:
    palette = file.read().splitlines()

go_nord = GoNord()
image = go_nord.open_image(expanduser(argv[1]))
go_nord.reset_palette()
[
    go_nord.add_color_to_palette(color.strip())
    for color in palette
    if not color.startswith("//") and color != ""
]
go_nord.convert_image(image, save_path=f"output-{datetime.now().strftime('%s')}.png")

# vim:ft=python
```

Depends on [ImageGoNord](https://github.com/Schrodinger-Hat/ImageGoNord-pip#getting-started).
and takes `colors.txt` from the current directory. 
Comments such as `//` are allowed
Example:
```txt
// Night
#36c692
#f87070
#f7d883
#ffe59e
#7ab0df
#1a1b23
```
lemme know how it turns out if you end up using it

**Comment by siduck** [comment]
@pagankeymaster do you like the colorscheme green or mine changes?

**Comment by siduck** [comment]
I can see that my changes look prettier BUT it looks similar to onedark and I feel like the theme name itself (radium) gives the feeling of glowy green >~<

**Comment by siduck** [comment]
i'll try to merge my changes and yours

**Comment by pagankeymaster** [comment]
> I can see that my changes look prettier BUT it looks similar to onedark and I feel like the theme name itself (radium) gives the feeling of glowy green >~<

heh I'm quite proud of that name.. came up with it today.. but I would use the one that is prettier !! 
also imo you should keep mine and apply the glowy blue from yours
or better use both variants like nord and onenord

**Comment by siduck** [comment]
> > I can see that my changes look prettier BUT it looks similar to onedark and I feel like the theme name itself (radium) gives the feeling of glowy green >~<
> 
> heh I'm quite proud of that name.. came up with it today.. but I would use the one that is prettier !! also imo you should keep mine and apply the glowy blue from yours or better use both variants like nord and onenord

now im confused! the rice i shared on the discord server was meant to be finalized, do you want the reddish one here or the discord one?

**Comment by pagankeymaster** [comment]
discord one is fine

**Pull request merged**
