### PR TITLE
Added Enki Theme by @enkia

### PR DESCRIPTION
**Pull request by ghost**
Preview:-
2023-01-12-183725_803x627_scrot

I was shocked to see that no one ported this theme before so i did

### CODE REVIEW

**Comment by siduck** [comment]
@sontaimnt  leave the theme toggle btn as it is, it should by default have lighter bg than tabuflinebg

**Comment by ghost** [comment]
Enki has another shade.. i can port it to nvchad

**Comment by ghost** [comment]
```lua
  TbLineThemeToggleBtn = {
    fg = M.base_30.white,
    bg = M.base_30.black,
  },
  ```
u mean this??

**Comment by siduck** [comment]
> ```lua
>  TbLineThemeToggleBtn = {
>    fg = M.base_30.white,
>    bg = M.base_30.black,
>  },
> ```
> 
> u mean this??

yes, you dont have to override it

**Comment by siduck** [comment]
hi @sontaimnt I will put this theme in v3.0 of nvchad! currently paused cuz v2.0 has 57 themes now

**Pull request closed without merging**
