### PR TITLE
Custom theme 'gatekeeper' based on base16-pico

### PR DESCRIPTION
**Pull request by Xulder**
Largely based on RRethy/nvim-base16 pico

### CODE REVIEW

**Comment by Xulder** [comment]
Not sure how well the colors balance out for everyone else, feedback would be appreciated!
pic-full-220509-1531-19
pic-full-220509-1531-45
pic-full-220509-1532-13

**Comment by Xulder** [comment]
I did?
`darker_black = "#0a0a0a",`
Am I missing something? because this should be 6% darker than #101010

**Comment by siduck** [comment]
image

see nvimtree looks lighter than editor bg

**Comment by Xulder** [comment]
Ohh yep okay I didn't even realize, thanks. Should be all good now! I lightened the folder text a little as well to compensate for the darker bg.

**Comment by siduck** [comment]
i'll polish this theme tomorrow!

**Comment by siduck** [comment]
image

**Review by siduck — APPROVED** [review]

**Pull request merged**
