### PR TITLE
Add extended_integrations

### PR DESCRIPTION
**Pull request by BrunoKrugel**
I kept the original colors from the plugins, so they have the original color but with our theme.

[weilbith/nvim-code-action-menu](https://github.com/weilbith/nvim-code-action-menu)
[todo-comments.nvim](https://github.com/folke/todo-comments.nvim)
[folke/trouble.nvim](https://github.com/folke/trouble.nvim)
[phaazon/hop.nvim](https://github.com/phaazon/hop.nvim)

### CODE REVIEW

**Comment by siduck** [comment]
@BrunoKrugel really appreciated, can you show how they look too :) ?

**Review by siduck — APPROVED** [review]

**Comment by BrunoKrugel** [comment]
Sure, with chadracula theme:

Hop
image

Todo
image

Trouble
image

Code action menu:
image

**Comment by siduck** [comment]
todo fix must be either green or yellow, rest are all fine!

**Comment by BrunoKrugel** [comment]
> todo fix must be either green or yellow, rest are all fine!

changed todo to yellow, regarding the red `fix`, its my config.

**Review by siduck — APPROVED** [review]

**Pull request merged**
