### PR TITLE
Added decay and darker decay themes

### PR DESCRIPTION
**Pull request by AlphaTechnolog**
# Decay themes

I'm pushing decay and darker decay themes for nvchad base46. Next i'll add a gallery of images of dark-decay and decay

# Showcase

## Decay

decay-1
decay-2
decay-3

## Dark decay

dark-decay1
dark-decay2
dark-decay3

### CODE REVIEW

**Comment by siduck** [comment]
@AlphaTechnolog looks cool! but I'll have to check out the old Pr's first, then I'll merge this :)

**Comment by AlphaTechnolog** [comment]
Np. Thank u for make this :3

**Review by siduck — APPROVED** [review]

**Comment by siduck** [comment]
@AlphaTechnolog the dark-decay doesnt look much different than decay so i removed it

**Comment by AlphaTechnolog** [comment]
Thank u mate, but the purpose of dark decay is have decay colors but with a more darker background, but ok no problem, thank you for include decay in nvchad :3

**Pull request merged**
