### PR TITLE
feat: yoru themes

### PR DESCRIPTION
**Pull request by rxyhn**
rxyhn -> yoru, changed some color accents(bg, fg, bright pallete). and also implemented the terms and conditions of NvChad theme

### CODE REVIEW

**Comment by siduck** [comment]
image

show how the theme looks akhi and what does   yoru mean?

**Comment by rxyhn** [comment]
image

yoru means `night` so yeah im currently use this colorscheme for my daily use, its so comfortable, dimmed background with high contrast accent is perfect for writing code in middle of the night

**Comment by siduck** [comment]
> image
> 
> yoru means `night` so yeah im currently use this colorscheme for my daily use, its so comfortable, dimmed background with high contrast accent is perfect for writing code in middle of the night

do :TSInstall go, and reopen  neovim & open that file

**Comment by rxyhn** [comment]
image

oh damn, i think i'll more love this

**Comment by ahhshm** [comment]
@siduck This is a breaking change. Please add an exponential mark (feat!) or the word "Breaking Change" to the commit message of the future breaking changes.

**Comment by siduck** [comment]
> @siduck This is a breaking change. Please add an exponential mark (feat!) or the word "Breaking Change" to the commit message of the future breaking changes.

i thought no one was using this theme so i let it slide off

**Comment by ahhshm** [comment]
> > @siduck This is a breaking change. Please add an exponential mark (feat!) or the word "Breaking Change" to the commit message of the future breaking changes.
> 
> i thought no one was using this theme so i let the commit name slide off

That was my favorite theme :) now it's not :(

**Comment by siduck** [comment]
> > > @siduck This is a breaking change. Please add an exponential mark (feat!) or the word "Breaking Change" to the commit message of the future breaking changes.
> > 
> > 
> > i thought no one was using this theme so i let the commit name slide off
> 
> That was my favorite theme :) now it's not :(

u liked the previous theme?

**Comment by ahhshm** [comment]
> > > > @siduck This is a breaking change. Please add an exponential mark (feat!) or the word "Breaking Change" to the commit message of the future breaking changes.
> > > 
> > > 
> > > i thought no one was using this theme so i let the commit name slide off
> > 
> > 
> > That was my favorite theme :) now it's not :(
> 
> u liked the previous theme?

Yeah, but the new one is also good. They are very much the same.

**Comment by siduck** [comment]
oh cool then, i was almost about to push the rxyhn theme back as a new theme file xD

**Comment by ahhshm** [comment]
> oh cool then, i was almost about to push the rxyhn theme back as a new theme file xD

It's not a bad idea though :)

**Comment by ahhshm** [comment]
Thank you

**Pull request merged**
