### PR TITLE
Add sweetpastel theme

### PR DESCRIPTION
**Pull request by Deathemonic**
I was bored so I create a base46 theme for my color scheme

Screenshots
Screenshot_2022-06-18-11-34-27_1280x800
Screenshot_2022-06-18-11-38-16_1280x800

```sh
local M = {}

M.base_30 = {
   white = "#F8F9FA",
   darker_black = "#1B1F23",
   black = "#212529", --  nvim bg
   black2 = "#343A40",
   one_bg = "#2b2f33", -- real bg of onedark
   one_bg2 = "#34383c",
   one_bg3 = "#3c4044",
   grey = "#ADB5BD",
   grey_fg = "#6C757D",
   grey_fg2 = "#495057",
   light_grey = "#CED4DA",
   red = "#FF8E8E",
   baby_pink = "#FFEDDE",
   pink = "#FFDEDE",
   line = "#343A40", -- for lines like vertsplit
   green = "#E4FFDE",
   vibrant_green = "#DFFFDE",
   nord_blue = "#DEF2FF",
   blue = "#DEFBFF",
   yellow = "#FFFBDE",
   sun = "#FFFDDE",
   purple = "#EFDEFF",
   dark_purple = "#EFDEFF",
   teal = "#DEFFE5",
   orange = "#FFE2C2",
   cyan = "#DEFBFF",
   statusline_bg = "#343A40",
   lightbg = "#495057",
   pmenu_bg = "#DEFBFF",
   folder_bg = "#FFDEDE",
}

M.base_16 = {
   base00 = "#212529",
   base01 = "#343A40",
   base02 = "#495057",
   base03 = "#6C757D",
   base04 = "#ADB5BD",
   base05 = "#CED4DA",
   base06 = "#DEE2E6",
   base07 = "#E9ECEF",
   base08 = "#FF8E8E",
   base09 = "#FFE2C2",
   base0A = "#FFFBDE",
   base0B = "#E4FFDE",
   base0C = "#DEFFE5",
   base0D = "#DEFBFF",
   base0E = "#EFDEFF",
   base0F = "#FC868C",
}

M.type = "dark"

M = require("base46").override_theme(M, "sweetpastel")

return M
```

### CODE REVIEW

**Comment by siduck** [comment]
looks nice, will test it locally first

**Comment by Deathemonic** [comment]
alright I'll just wait

**Comment by siduck** [comment]
@Deathemonic so #FFDEDE is the fg right?  Im going to replace some colors

**Comment by siduck** [comment]
for example the red color isnt fit for a pastel theme 
image

**Comment by siduck** [comment]
@Deathemonic improved the theme 

image

**Review by siduck — APPROVED** [review]

**Comment by Deathemonic** [comment]
> for example the red color isnt fit for a pastel theme 
> image
> 

yeah I also have the same thoughts about red it really doesn't feel like pastel

**Comment by Deathemonic** [comment]
> @Deathemonic improved the theme 
> 
> image
> 

damn this is really nice

**Comment by Deathemonic** [comment]
> @Deathemonic so #FFDEDE is the fg right?  Im going to replace some colors

@siduck the #FFDEDE is actually #FFBEBE

**Comment by siduck** [comment]
yea i took actual pastel colors from various images, like pastel foods https://www.google.com/search?q=pastel%20color%20food%20teal&tbm=isch&hl=en&tbs=rimg:CTCR6NO8wCVXYUA-I7Bx4lML8AEAsgIOCgIIABAAKAE6BAgBEAE&sa=X&ved=0CBsQuIIBahcKEwjQ9bblj9T4AhUAAAAAHQAAAAAQPQ&biw=1723&bih=857#imgrc=NtvCU9EY6YvNGM xD

**Comment by Deathemonic** [comment]
oh ok it's nice that it's based on those because my version is base in this wallpaper 
https://www.wallpaperflare.com/headphones-minimalism-pastel-pink-wallpaper-cuaug

because it's vibriant

**Pull request merged**
