### PR TITLE
Adds decayce theme to base46

### PR DESCRIPTION
**Pull request by AlphaTechnolog**
# Decay (Decayce)

Hello! So i wanted to include the decay (decayce variant) in the base46 repo, here is the pull-request :>

Looks like this rn:

decayce

### CODE REVIEW

**Comment by siduck** [comment]
darker_black needs to be 4% darker 
black2 needs to be 5% lighter 

and this color needs to be 10% darker
image

**Comment by AlphaTechnolog** [comment]
Okok, I'll do that then. Thanks

**Comment by siduck** [comment]
@AlphaTechnolog sorry but i'll be closing this! it looks very similar to decay theme

**Comment by AlphaTechnolog** [comment]
Tbh it can't be totally possible, decayce is a totally remake of decay that aims to make decay more icy and darken, so it can't look very similar. I just need to remake the background hexes but the base16 colors and the backgrounds ones are remaked from scratch :/

**Comment by siduck** [comment]
@AlphaTechnolog it looks the same to me as before :( , probably the hex colors would be different but the physical look looks the same imo

**Comment by AlphaTechnolog** [comment]
Its ok then, I'll redistribute it in another way then. Thank you for everything anyways hahaha

**Comment by siduck** [comment]
> Its ok then, I'll redistribute it in another way then. Thank you for everything anyways hahaha

yep make some theme which looks new, you can get inspiration from here :D
https://themes.vscode.one/

**Pull request closed without merging**
