### PR TITLE
add integration for notify plugin

### PR DESCRIPTION
**Pull request by shashanktomar**
I have kept the same colors that notify use as highlights. If you have better suggestions, I can make the change.

### CODE REVIEW

**Comment by siduck** [comment]
show your nvim-notify packerconfig so i could test it here :D

**Comment by shashanktomar** [comment]
This is my config for notify:
```lua
local ok, notify = pcall(require, "notify")

if not ok then
 return
end

require("base46").load_highlight "notify"

local options = {
	stages = "fade_in_slide_out",
	timeout = 2000,
}

notify.setup(options)
vim.notify = notify

```

**Comment by shashanktomar** [comment]
Hi @siduck, i hope this is good to go?

**Comment by siduck** [comment]
@shashanktomar good job!

**Pull request merged**
