### PR TITLE
Add Fizzner Theme

### PR DESCRIPTION
**Pull request by micahkepe**
A custom theme that I made that is a middle ground between Onedark, Palenight, and TokyoNight

### CODE REVIEW

**Comment by siduck** [comment]
show pic!

**Comment by micahkepe** [comment]
Screenshot 2024-10-17 at 3 13 49 PM

**Comment by siduck** [comment]
i think this looks like onedark almost

**Comment by siduck** [comment]
i need unique themes in base46 v3.0

**Pull request closed without merging**
